### DISCUSSION TITLE
Prometheus exporter: target name

### DISCUSSION THREAD

**Discussion by mpergament** [openconfig/gnmi-gateway#54] [Q&A]
```
---
connection:
  demo-gnmi-router:
    addresses:
      - 10.100.164.130:6030
    credentials:
      username: test
      password: test
    request: demo-request
    meta:  
      NoTLSVerify: "yes"
request:
  demo-request:
    target: "*"
    paths:
      - /interfaces/interface[name=*]/state/counters
      - /interfaces/interface[name=*]/ethernet/state/counters
```

This results in target set to *:
```
interfaces_interface_state_counters_out_octets{instance="192.168.178.46:59100", interfaces_interface_name="Ethernet15/2", job="gnmi", target="*"} | 15073

interfaces_interface_state_counters_out_octets{instance="192.168.178.46:59100", interfaces_interface_name="Ethernet21/1", job="gnmi", target="*"}
```

If I have multiple devices I would expect to see device name as a target. Is there any way to achieve it?
